#include "src/game/envfx_snow.h"

const GeoLayout aria_Head_Dead__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Head_Down__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Down_Switch_Option_Head_Down_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Down_Switch_Option_Head_Down_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Head_Left__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Left_Switch_Option_Head_Left_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Left_Switch_Option_Head_Left_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Head_Up__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Up_Switch_Option_Head_Up_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Up_Switch_Option_Head_Up_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Head_Right__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Right_Switch_Option_Head_Right_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Right_Switch_Option_Head_Right_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesHalf_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesHalf_1),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesHalf_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesClosed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesClosed_2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesClosed_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesLeft_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesLeft_3),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesLeft_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesRight_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesRight_4),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesRight_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesUP_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesUP_5),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesUP_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesDown_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesDown_6),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesDown_6),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesDed_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesDed_7),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesDed_7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5),
				GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Dead__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Down__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Down_Switch_Option_Head_Down_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Down_Switch_Option_Head_Down_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Left__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Left_Switch_Option_Head_Left_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Left_Switch_Option_Head_Left_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Up__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Up_Switch_Option_Head_Up_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Up_Switch_Option_Head_Up_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Right__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Right_Switch_Option_Head_Right_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Right_Switch_Option_Head_Right_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesHalf_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesHalf_1),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesHalf_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesClosed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesClosed_2),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesClosed_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesLeft_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesLeft_3),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesLeft_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesRight_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesRight_4),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesRight_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesUP_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesUP_5),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesUP_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesDown_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesDown_6),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesDown_6),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesDed_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesDed_7),
		GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_EyesDed_7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5),
				GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_1_mat_override_EyesHalf_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesHalf_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_1_mat_override_EyesClosed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesClosed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_1_mat_override_EyesLeft_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesLeft_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_1_mat_override_EyesRight_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesRight_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_1_mat_override_EyesUP_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesUP_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_1_mat_override_EyesDown_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesDown_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, -5, 0, aria_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 122, 9, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Dead__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Down__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Left__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Up__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Head_Right__Optional_),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Capless_Head),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 7, 50, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Left_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, aria_Left_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Left_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Left_Hand_Open),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 7, -50, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Right_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, aria_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Open),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Peace),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Cap),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_aria_Right_Hand_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 1, 35, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Left_Thigh_Color_mesh_layer_5),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 2, aria_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 84, 0, 5, aria_Left_Shoe_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, -33, -13, 25, -13, 40, 165),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 1, -36, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Thigh_Color_mesh_layer_5),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, -1, aria_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, -5, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, -33, -13, -26, 17, -41, 157),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Wing_DL_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Shoe_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Dead__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Down__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Down_Switch_Option_Head_Down_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Down_Switch_Option_Head_Down_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Left__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Left_Switch_Option_Head_Left_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Left_Switch_Option_Head_Left_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Up__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Up_Switch_Option_Head_Up_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Up_Switch_Option_Head_Up_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Right__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_Right_Switch_Option_Head_Right_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Right_Switch_Option_Head_Right_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_Metal_0),
				GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_Metal_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal_0),
		GEO_OPEN_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, aria_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Butt_mesh_layer_1_mat_override_Metal_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 60, -5, 0, aria_Torso_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 122, 9, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_Metal_0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Dead__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Down__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Left__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Up__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Head_Right__Optional_),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Capless_Head),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 7, 50, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Left_Arm_Color_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, aria_Left_Forearm_mesh_layer_1_mat_override_Metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Left_Hand_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Left_Hand_Open),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 7, -50, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Right_Arm_Color_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, aria_Right_Forearm_mesh_layer_1_mat_override_Metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Right_Hand_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Open),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Peace),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Cap),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_aria_Right_Hand_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 1, 35, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Left_Thigh_Color_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Left_Thigh_Color_mesh_layer_5_mat_override_Metal_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 2, aria_Left_Leg_mesh_layer_1_mat_override_Metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, 5, aria_Left_Shoe_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, -33, -13, 25, -13, 40, 165),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, aria_Left_Wing_DL_mesh_layer_4_mat_override_Metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 1, -36, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Right_Thigh_Color_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Thigh_Color_mesh_layer_5_mat_override_Metal_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -1, aria_Right_Leg_mesh_layer_1_mat_override_Metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, -5, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, -33, -13, -26, 17, -41, 157),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_ALPHA, aria_Right_Wing_DL_mesh_layer_4_mat_override_Metal_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Right_Shoe_DL_mesh_layer_1_mat_override_Metal_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Dead__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Down__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Down_Switch_Option_Head_Down_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Down_Switch_Option_Head_Down_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Left__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Left_Switch_Option_Head_Left_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Left_Switch_Option_Head_Left_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Up__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Up_Switch_Option_Head_Up_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Up_Switch_Option_Head_Up_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Right__Optional_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Right_Switch_Option_Head_Right_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_Right_Switch_Option_Head_Right_mesh_layer_5_mat_override_Metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Metal_0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_Metal_0),
				GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, 135, -112, -8),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Capless_Head_Switch_Option_Hair2DL_mesh_layer_1_mat_override_Metal_0),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal_0),
		GEO_OPEN_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, aria_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Butt_mesh_layer_1_mat_override_Metal_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, -5, 0, aria_Torso_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 122, 9, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_Metal_0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Dead__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Down__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Left__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Up__Optional_),
											GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Head_Right__Optional_),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Capless_Head),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 7, 50, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Left_Arm_Color_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, aria_Left_Forearm_mesh_layer_1_mat_override_Metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Left_Hand_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Left_Hand_Open),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 7, -50, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Right_Arm_Color_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, aria_Right_Forearm_mesh_layer_1_mat_override_Metal_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Hand_DL_mesh_layer_1_mat_override_Metal_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Open),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Peace),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Cap),
										GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_aria_Right_Hand_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 1, 35, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Left_Thigh_Color_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Left_Thigh_Color_mesh_layer_5_mat_override_Metal_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 2, aria_Left_Leg_mesh_layer_1_mat_override_Metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 84, 0, 5, aria_Left_Shoe_mesh_layer_1_mat_override_Metal_0),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, -33, -13, 25, -13, 40, 165),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Left_Wing_DL_mesh_layer_4_mat_override_Metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 1, -36, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, aria_Right_Thigh_Color_mesh_layer_1_mat_override_Metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Thigh_Color_mesh_layer_5_mat_override_Metal_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, -1, aria_Right_Leg_mesh_layer_1_mat_override_Metal_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, -5, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_FORCE, -33, -13, -26, 17, -41, 157),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Wing_DL_mesh_layer_4_mat_override_Metal_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Shoe_DL_mesh_layer_1_mat_override_Metal_0),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_DL_mesh_layer_1_mat_override_EyesHalf_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesHalf_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_DL_mesh_layer_1_mat_override_EyesClosed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesClosed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_DL_mesh_layer_1_mat_override_EyesLeft_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesLeft_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_DL_mesh_layer_1_mat_override_EyesRight_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesRight_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_DL_mesh_layer_1_mat_override_EyesUP_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesUP_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_DL_mesh_layer_1_mat_override_EyesDown_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5_mat_override_EyesDown_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout aria_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, -5, 0, aria_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 122, 9, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Head_DL_mesh_layer_1),
																		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Head_DL_mesh_layer_5),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1),
																	GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2),
																	GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3),
																	GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4),
																	GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5),
																	GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6),
																	GEO_BRANCH(1, aria_Head_Dead__Optional_),
																	GEO_BRANCH(1, aria_Head_Down__Optional_),
																	GEO_BRANCH(1, aria_Head_Left__Optional_),
																	GEO_BRANCH(1, aria_Head_Up__Optional_),
																	GEO_BRANCH(1, aria_Head_Right__Optional_),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, aria_Capless_Head),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 7, 50, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Left_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, aria_Left_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Left_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, aria_Left_Hand_Open),
																GEO_BRANCH(1, aria_Right_Hand_Wing_Cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 7, -50, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Right_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, aria_Right_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 72, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Right_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, aria_Right_Hand_Open),
																GEO_BRANCH(1, aria_Right_Hand_Peace),
																GEO_BRANCH(1, aria_Right_Hand_Cap),
																GEO_BRANCH(1, aria_Right_Hand_Cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 1, 35, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Left_Thigh_Color_mesh_layer_5),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 2, aria_Left_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, 5, aria_Left_Shoe_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, -33, -13, 25, -13, 40, 165),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, aria_Left_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 13, 1, -36, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, aria_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_Right_Thigh_Color_mesh_layer_5),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -1, aria_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 84, 0, -5, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_TRANSLATE_ROTATE(LAYER_FORCE, -33, -13, -26, 17, -41, 157),
															GEO_OPEN_NODE(),
																GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
																GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_ALPHA, aria_Right_Wing_DL_mesh_layer_4),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_Right_Shoe_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt2),
							GEO_BRANCH(1, aria_2_LoD_Switch_opt0_Cap_State_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, aria_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, aria_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, aria_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
