extern const GeoLayout a_acc_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout a_acc_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout a_acc_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout a_acc_geo[];
extern Lights1 a_acc_Thingy2_lights;
extern Lights1 a_acc_Thingy1_lights;
extern Lights1 a_acc_Metal_lights;
extern u8 a_acc_metal_rgba16_rgba16[];
extern u8 a_acc_Metal_Light_rgba16_rgba16[];
extern Vtx a_acc_Normal_Cap_DL_mesh_layer_1_vtx_0[70];
extern Gfx a_acc_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx a_acc_Normal_Cap_DL_mesh_layer_1_vtx_1[72];
extern Gfx a_acc_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_a_acc_Thingy2[];
extern Gfx mat_revert_a_acc_Thingy2[];
extern Gfx mat_a_acc_Thingy1[];
extern Gfx mat_revert_a_acc_Thingy1[];
extern Gfx mat_a_acc_Metal[];
extern Gfx mat_revert_a_acc_Metal[];
extern Gfx a_acc_Normal_Cap_DL_mesh_layer_1[];
extern Gfx a_acc_Normal_Cap_DL_mesh_layer_1_mat_override_Metal_0[];
extern Gfx a_acc_material_revert_render_settings[];
