extern const GeoLayout a_acc_wing_Wing_Cap_Switch_opt1[];
extern const GeoLayout a_acc_wing_Wing_Cap_Switch_opt2[];
extern const GeoLayout a_acc_wing_Wing_Cap_Switch_opt3[];
extern const GeoLayout a_acc_wing_geo[];
extern Lights1 a_acc_wing_Boots2_lights;
extern Lights1 a_acc_wing_Boots_lights;
extern Lights1 a_acc_wing_Metal_lights;
extern u8 a_acc_wing_metal_rgba16_rgba16[];
extern u8 a_acc_wing_Metal_Light_rgba16_rgba16[];
extern u8 a_acc_wing_wing_2_rgba16[];
extern u8 a_acc_wing_wing1_rgba16[];
extern Vtx a_acc_wing_Wing_Cap_mesh_layer_1_vtx_0[54];
extern Gfx a_acc_wing_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx a_acc_wing_Wing_Cap_mesh_layer_1_vtx_1[88];
extern Gfx a_acc_wing_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx a_acc_wing_Wings_mesh_layer_4_vtx_0[8];
extern Gfx a_acc_wing_Wings_mesh_layer_4_tri_0[];
extern Vtx a_acc_wing_Wings_mesh_layer_4_vtx_1[8];
extern Gfx a_acc_wing_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_a_acc_wing_Boots2[];
extern Gfx mat_revert_a_acc_wing_Boots2[];
extern Gfx mat_a_acc_wing_Boots[];
extern Gfx mat_revert_a_acc_wing_Boots[];
extern Gfx mat_a_acc_wing_Metal[];
extern Gfx mat_revert_a_acc_wing_Metal[];
extern Gfx mat_a_acc_wing_Wing_Tip[];
extern Gfx mat_revert_a_acc_wing_Wing_Tip[];
extern Gfx mat_a_acc_wing_Wing_Base[];
extern Gfx mat_revert_a_acc_wing_Wing_Base[];
extern Gfx a_acc_wing_Wing_Cap_mesh_layer_1[];
extern Gfx a_acc_wing_Wing_Cap_mesh_layer_1_mat_override_Metal_0[];
extern Gfx a_acc_wing_Wings_mesh_layer_4[];
extern Gfx a_acc_wing_Wings_mesh_layer_4_mat_override_Metal_0[];
extern Gfx a_acc_wing_material_revert_render_settings[];
